window.addEventListener('DOMContentLoaded', (event) => {
	console.log("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX CS LOADED")
	console.log("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX CS LOADED")
	console.log("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX CS LOADED")
	console.log("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX CS LOADED")
	console.log("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX CS LOADED")
	console.log("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX CS LOADED")
});

console.log("YYYYYYYYYYY CS LOADED")
	console.log("YYYYYYYYYYY CS LOADED")
	console.log("YYYYYYYYYYY CS LOADED")
	console.log("YYYYYYYYYYY CS LOADED")
	console.log("YYYYYYYYYYY CS LOADED")
	console.log("YYYYYYYYYYY CS LOADED")